import React, { useState } from 'react';
import Head from 'next/head';
import { Button } from '@mui/material';
import ReviewModal from '@/components/forms/ReviewForms';
export default function Home() {
  const [modalOpen, setModalOpen] = useState(false);

  const handleModalOpen = () => {
    setModalOpen(true);
  };

  const handleModalClose = () => {
    setModalOpen(false);
  };

  return (
    <>
      <Head>
        <title>Cultura sin fronteras</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>¡Hola mundo!</h1>
      <Button variant="contained" color="primary" onClick={handleModalOpen}>
        Deja un review
      </Button>
      <ReviewModal open={modalOpen} onClose={handleModalClose} /> {/* Renderiza el modal */}
    </>
  );
}
