import Head from 'next/head'
import EventCard from '@/components/Cards/Event'

import React, { useState } from 'react';
import { Button } from '@mui/material';
import ReviewModal from '@/components/Forms/ReviewForms';

export default function Home() {
  const [modalOpen, setModalOpen] = useState(false);

  const handleModalOpen = () => {
    setModalOpen(true);
  };

  const handleModalClose = () => {
    setModalOpen(false);
  };

  return (
    <>
      <Head>
        <title>Cultura sin fronteras</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EventCard
        imageUrl="https://source.unsplash.com/345x140/?travel"
        name="Viaje a la luna"
        startDate="2022-12-12"
        endDate="2022-12-13"
        rating={4}
        id={1}
      />
      {/* <Button variant="contained" color="primary" onClick={handleModalOpen}>
        Deja un review
      </Button> */}
      <ReviewModal open={modalOpen} onClose={handleModalClose} />
    </>
  );
}
