import Head from 'next/head'
import EventCard from '@/components/Cards/Event'

export default function Home() {
  return (
    <>
      <Head>
        <title>Cultura sin fronteras</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EventCard
        imageUrl="https://source.unsplash.com/345x140/?travel"
        name="Viaje a la luna"
        startDate="2022-12-12"
        endDate="2022-12-13"
        rating={4}
        id={1}
      />
    </>
  )
}
